version: "3.8"
services:
  sqs-consumer-worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=dummy-access-key
      - AWS_SECRET_ACCESS_KEY=dummy-secret-key
    depends_on:
      - localstack
    links:
      - localstack
    command: ["dotnet", "sqs-consumer-worker.dll"]
